set(SRC_FILES
        App.cpp
        ResourceManager.cpp
        controller/DifficultyController.cpp
        controller/GameController.cpp
        controller/ResultController.cpp
        controller/StartController.cpp
        model/AttackTowerBase.cpp
        model/BuildableRegistry.cpp
        model/ConcreteTowers.cpp
        model/DifficultyModel.cpp
        model/EnemyModel.cpp
        model/GameModel.cpp
        model/GameStates.cpp
        model/MapFactory.cpp
        model/MapModel.cpp
        model/PlacementModel.cpp
        model/ProjectileModel.cpp
        model/ResultModel.cpp
        model/StartModel.cpp
        model/TowerBase.cpp
        model/TrapBase.cpp
        model/WaveConfig.cpp
        scene/DifficultyScene.cpp
        scene/GameScene.cpp
        scene/ResultScene.cpp
        scene/SceneManager.cpp
        scene/StartScene.cpp
        view/DifficultyView.cpp
        view/GameView.cpp
        view/ResultView.cpp
        view/StartView.cpp
        view/UIView.cpp
)

set(INCLUDE_FILES
        GameConfig.h
        ResourceManager.h
        SceneType.h
        controller/DifficultyController.h
        controller/GameController.h
        controller/ResultController.h
        controller/StartController.h
        controller/commands/ICommand.h
        controller/commands/ReturnToDifficultyCommand.h
        controller/commands/SelectBuildableCommand.h
        controller/commands/SellTowerCommand.h
        controller/commands/StartRoundCommand.h
        controller/commands/UpgradeTowerCommand.h
        model/AttackTowerBase.h
        model/BuildableRegistry.h
        model/ConcreteTowers.h
        model/DifficultyModel.h
        model/EnemyModel.h
        model/GameModel.h
        model/GameStates.h
        model/HitEffectEmitter.h
        model/HitEffectEvent.h
        model/IBuildable.h
        model/IGameState.h
        model/MapData.h
        model/MapFactory.h
        model/MapModel.h
        model/PlacementModel.h
        model/ProjectileModel.h
        model/ResultModel.h
        model/StartModel.h
        model/StatusEffects/BurnEffect.h
        model/StatusEffects/FreezeEffect.h
        model/StatusEffects/IStatusEffect.h
        model/StatusEffects/PoisonEffect.h
        model/StatusEffects/SlowEffect.h
        model/TowerBase.h
        model/TrapBase.h
        model/WaveConfig.h
        scene/DifficultyScene.h
        scene/GameScene.h
        scene/IScene.h
        scene/ResultScene.h
        scene/SceneManager.h
        scene/StartScene.h
        view/DifficultyView.h
        view/GameUILayout.h
        view/GameView.h
        view/ResultView.h
        view/StartView.h
        view/UIView.h
        App.hpp
        nlohmann/json.hpp
)

set(TEST_FILES)
